<template>
  <ion-page>
    <ion-content :fullscreen="true">
      <main class="role-page"><header><a href="/login" class="back"><ion-icon :icon="arrowBackOutline" /> Back to login</a><BrandMark /><span class="dev-pill"><ion-icon :icon="codeSlashOutline" /> Development preview</span></header><section class="role-heading"><p class="kicker">MOCK ROLE SELECTION</p><h1>Choose an interface to preview.</h1><p>There are four UI roles in the BarkoLink prototype. No real authentication is connected yet.</p></section><section class="role-grid"><article v-for="role in roles" :key="role.key" :class="['role-card', role.tone]"><span class="role-icon"><ion-icon :icon="role.icon" /></span><div><p class="role-type">{{ role.type }}</p><h2>{{ role.title }}</h2><p>{{ role.description }}</p></div><a :href="role.path" class="open-role">Open interface <ion-icon :icon="arrowForwardOutline" /></a></article></section><div class="role-note"><ion-icon :icon="informationCircleOutline" /><span>These role previews use mock data only and can be removed when real authentication is introduced.</span></div></main>
    </ion-content>
  </ion-page>
</template>
<script setup lang="ts">
import { IonContent, IonIcon, IonPage } from '@ionic/vue'
import { arrowBackOutline, arrowForwardOutline, boatOutline, codeSlashOutline, informationCircleOutline, peopleOutline, personOutline, shieldCheckmarkOutline } from 'ionicons/icons'
import BrandMark from '../../components/BrandMark.vue'
const ticketIcon = peopleOutline
const roles = [{ key:'passenger',type:'PASSENGER',title:'Passenger',description:'Search sailings, book a trip, manage tickets, and receive travel alerts.',path:'/home',tone:'blue',icon:personOutline },{ key:'ticketing',type:'STAFF ROLE 01',title:'Ticketing Staff',description:'Create and manage bookings, review passengers, and update ticket status.',path:'/staff/ticketing',tone:'mint',icon:ticketIcon },{ key:'boarding',type:'STAFF ROLE 02',title:'Boarding Staff',description:'Check tickets, verify check-in, and manage boarding activity at the port.',path:'/staff/boarding',tone:'amber',icon:boatOutline },{ key:'administrator',type:'STAFF ROLE 03',title:'Administrator',description:'Monitor operations, manage schedules, vessels, users, reports, and settings.',path:'/admin',tone:'navy',icon:shieldCheckmarkOutline }]
</script>
<style scoped>
.role-page{max-width:980px;margin:0 auto;padding:28px 34px 70px}.role-page header{display:flex;align-items:center;justify-content:space-between}.back{display:flex;align-items:center;gap:6px;color:var(--muted);font-size:11px;text-decoration:none}.back ion-icon{font-size:17px}.dev-pill{display:flex;align-items:center;gap:5px;padding:7px 9px;border-radius:7px;background:var(--light-blue);color:var(--ocean);font-size:9px;font-weight:800}.role-heading{margin:85px 0 30px;max-width:590px}.role-heading h1{margin:9px 0 7px;font-size:36px;letter-spacing:-1.2px}.role-heading>p:last-child{margin:0;color:var(--muted);font-size:13px;line-height:1.6}.kicker{margin:0;color:var(--ocean);font-size:10px;font-weight:800;letter-spacing:.11em}.role-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.role-card{position:relative;display:flex;flex-direction:column;min-height:230px;padding:22px;border:1px solid var(--line);border-radius:17px;background:var(--surface);overflow:hidden}.role-card:after{content:'';position:absolute;right:-42px;top:-42px;width:125px;height:125px;border-radius:50%;background:rgba(33,150,243,.08)}.role-icon{display:grid;place-items:center;width:42px;height:42px;margin-bottom:28px;border-radius:12px;font-size:21px}.role-card.blue .role-icon{background:var(--light-blue);color:var(--ocean)}.role-card.mint .role-icon{background:#def7f0;color:#078a72}.role-card.amber .role-icon{background:#fff1d2;color:#b77700}.role-card.navy{background:var(--deep);color:#fff;border-color:var(--deep)}.role-card.navy .role-icon{background:#173b61;color:#7cc4e5}.role-type{margin:0 0 7px;color:var(--ocean);font-size:9px;font-weight:800;letter-spacing:.1em}.role-card.navy .role-type{color:#7cc4e5}.role-card h2{margin:0;font-size:20px}.role-card>div>p:last-child{max-width:300px;margin:8px 0 0;color:var(--muted);font-size:11px;line-height:1.5}.role-card.navy>div>p:last-child{color:#a7bfd0}.open-role{display:flex;align-items:center;gap:5px;margin-top:auto;padding-top:20px;color:var(--ocean);font-size:11px;font-weight:800;text-decoration:none}.role-card.navy .open-role{color:#7cc4e5}.open-role ion-icon{font-size:15px}.role-note{display:flex;align-items:center;gap:7px;margin-top:20px;color:var(--muted);font-size:10px}.role-note ion-icon{color:var(--ocean);font-size:16px}@media(max-width:650px){.role-page{padding:20px 16px 50px}.role-page header :deep(.brand-copy small){display:none}.role-heading{margin:55px 0 25px}.role-heading h1{font-size:29px}.role-grid{grid-template-columns:1fr}.role-card{min-height:190px}.role-icon{margin-bottom:20px}.dev-pill{font-size:8px}}
</style>
